<?xml version="1.0" encoding="UTF-8"?><testrun name="JIntegerNaturalNumberTest" project="Numbers" tests="4" started="4" failures="1" errors="0" ignored="0">
  <testsuite name="test.numbers.JIntegerNaturalNumberTest" time="0.02">
    <testsuite name="test.numbers.JIntegerNaturalNumberTest.Comparison" time="0.01">
      <testsuite name="test.numbers.JIntegerNaturalNumberTest.Comparison.Equal" time="0.01">
        <testcase name="oneAndTenAreNotEqual" classname="test.numbers.JIntegerNaturalNumberTest.Comparison.Equal" time="0.01"/>
        <testcase name="tenAndTwentyAreNotEqual" classname="test.numbers.JIntegerNaturalNumberTest.Comparison.Equal" time="0.0"/>
        <testcase name="sameNumberAreEquals" classname="test.numbers.JIntegerNaturalNumberTest.Comparison.Equal" time="0.0"/>
      </testsuite>
    </testsuite>
    <testsuite name="test.numbers.JIntegerNaturalNumberTest.Constructors" time="0.01">
      <testcase name="intAndListOfBytesConstructorsReturnSameNumber" classname="test.numbers.JIntegerNaturalNumberTest.Constructors" time="0.01">
        <failure>java.lang.AssertionError: 
Expected: is &lt;32&gt;
     but: was &lt;123&gt;&#13;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)&#13;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)&#13;
	at test.numbers.JIntegerNaturalNumberTest$Constructors.intAndListOfBytesConstructorsReturnSameNumber(JIntegerNaturalNumberTest.java:52)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at de.bechte.junit.runners.context.statements.StatementExecutor.execute(StatementExecutor.java:28)&#13;
	at de.bechte.junit.runners.context.processing.MethodExecutor.run(MethodExecutor.java:83)&#13;
	at de.bechte.junit.runners.context.processing.MethodExecutor.run(MethodExecutor.java:57)&#13;
	at de.bechte.junit.runners.context.statements.RunChildren.evaluate(RunChildren.java:38)&#13;
	at de.bechte.junit.runners.context.statements.RunAll.evaluate(RunAll.java:27)&#13;
	at de.bechte.junit.runners.context.statements.StatementExecutor.execute(StatementExecutor.java:28)&#13;
	at de.bechte.junit.runners.context.HierarchicalContextRunner.run(HierarchicalContextRunner.java:134)&#13;
	at de.bechte.junit.runners.context.processing.ContextExecutor.run(ContextExecutor.java:26)&#13;
	at de.bechte.junit.runners.context.processing.ContextExecutor.run(ContextExecutor.java:15)&#13;
	at de.bechte.junit.runners.context.statements.RunChildren.evaluate(RunChildren.java:38)&#13;
	at de.bechte.junit.runners.context.statements.RunAll.evaluate(RunAll.java:27)&#13;
	at de.bechte.junit.runners.context.statements.StatementExecutor.execute(StatementExecutor.java:28)&#13;
	at de.bechte.junit.runners.context.HierarchicalContextRunner.run(HierarchicalContextRunner.java:134)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
      </testcase>
    </testsuite>
  </testsuite>
</testrun>
