<?xml version="1.0" encoding="UTF-8"?><testrun name="PrimeNumbersCalculatorTest" project="Numbers" tests="12" started="12" failures="0" errors="1" ignored="1">
  <testsuite name="test.numbers.PrimeNumbersCalculatorTest" time="0.0">
    <testsuite name="test.numbers.PrimeNumbersCalculatorTest.FindPrimeNumbersUpTo" time="0.0">
      <testsuite name="test.numbers.PrimeNumbersCalculatorTest.FindPrimeNumbersUpTo.TestResult" time="0.0">
        <testcase name="ZERO_returnsEmpty" classname="test.numbers.PrimeNumbersCalculatorTest.FindPrimeNumbersUpTo.TestResult" time="0.0"/>
        <testcase name="Four_returns_2_3" classname="test.numbers.PrimeNumbersCalculatorTest.FindPrimeNumbersUpTo.TestResult" time="0.0"/>
        <testcase name="Two_returns_2" classname="test.numbers.PrimeNumbersCalculatorTest.FindPrimeNumbersUpTo.TestResult" time="0.0"/>
        <testcase name="Three_returns_2_3" classname="test.numbers.PrimeNumbersCalculatorTest.FindPrimeNumbersUpTo.TestResult" time="0.0"/>
        <testcase name="Eleven_returns_2_3_5_7_11" classname="test.numbers.PrimeNumbersCalculatorTest.FindPrimeNumbersUpTo.TestResult" time="0.0"/>
        <testcase name="Twelve_returns_2_3_5_7_11" classname="test.numbers.PrimeNumbersCalculatorTest.FindPrimeNumbersUpTo.TestResult" time="0.0"/>
        <testcase name="One_returnsEmpty" classname="test.numbers.PrimeNumbersCalculatorTest.FindPrimeNumbersUpTo.TestResult" time="0.0"/>
      </testsuite>
    </testsuite>
    <testsuite name="test.numbers.PrimeNumbersCalculatorTest.GetNextPrimeNumber" time="0.0">
      <testsuite name="test.numbers.PrimeNumbersCalculatorTest.GetNextPrimeNumber.TestResult" time="0.0">
        <testcase name="called_four_times" classname="test.numbers.PrimeNumbersCalculatorTest.GetNextPrimeNumber.TestResult" time="0.0" ignored="true"/>
        <testcase name="after_2_is_3" classname="test.numbers.PrimeNumbersCalculatorTest.GetNextPrimeNumber.TestResult" time="0.0">
          <error>java.lang.IndexOutOfBoundsException: Index: 2, Size: 2&#13;
	at java.util.ArrayList.rangeCheck(Unknown Source)&#13;
	at java.util.ArrayList.get(Unknown Source)&#13;
	at main.numbers.PrimeNumbersCalculator.getNextPrimeNumber(PrimeNumbersCalculator.java:29)&#13;
	at main.numbers.PrimeNumbersCalculator.getNextPrimeNumber(PrimeNumbersCalculator.java:20)&#13;
	at test.numbers.PrimeNumbersCalculatorTest$GetNextPrimeNumber.computeAndCheck(PrimeNumbersCalculatorTest.java:42)&#13;
	at test.numbers.PrimeNumbersCalculatorTest$GetNextPrimeNumber.after(PrimeNumbersCalculatorTest.java:49)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)&#13;
	at de.bechte.junit.runners.context.statements.StatementExecutor.execute(StatementExecutor.java:28)&#13;
	at de.bechte.junit.runners.context.processing.MethodExecutor.run(MethodExecutor.java:83)&#13;
	at de.bechte.junit.runners.context.processing.MethodExecutor.run(MethodExecutor.java:57)&#13;
	at de.bechte.junit.runners.context.statements.RunChildren.evaluate(RunChildren.java:38)&#13;
	at de.bechte.junit.runners.context.statements.RunAll.evaluate(RunAll.java:27)&#13;
	at de.bechte.junit.runners.context.statements.StatementExecutor.execute(StatementExecutor.java:28)&#13;
	at de.bechte.junit.runners.context.HierarchicalContextRunner.run(HierarchicalContextRunner.java:134)&#13;
	at de.bechte.junit.runners.context.processing.ContextExecutor.run(ContextExecutor.java:26)&#13;
	at de.bechte.junit.runners.context.processing.ContextExecutor.run(ContextExecutor.java:15)&#13;
	at de.bechte.junit.runners.context.statements.RunChildren.evaluate(RunChildren.java:38)&#13;
	at de.bechte.junit.runners.context.statements.RunAll.evaluate(RunAll.java:27)&#13;
	at de.bechte.junit.runners.context.statements.StatementExecutor.execute(StatementExecutor.java:28)&#13;
	at de.bechte.junit.runners.context.HierarchicalContextRunner.run(HierarchicalContextRunner.java:134)&#13;
	at de.bechte.junit.runners.context.processing.ContextExecutor.run(ContextExecutor.java:26)&#13;
	at de.bechte.junit.runners.context.processing.ContextExecutor.run(ContextExecutor.java:15)&#13;
	at de.bechte.junit.runners.context.statements.RunChildren.evaluate(RunChildren.java:38)&#13;
	at de.bechte.junit.runners.context.statements.RunAll.evaluate(RunAll.java:27)&#13;
	at de.bechte.junit.runners.context.statements.StatementExecutor.execute(StatementExecutor.java:28)&#13;
	at de.bechte.junit.runners.context.HierarchicalContextRunner.run(HierarchicalContextRunner.java:134)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</error>
        </testcase>
        <testcase name="after_2_3_5_is_7" classname="test.numbers.PrimeNumbersCalculatorTest.GetNextPrimeNumber.TestResult" time="0.0"/>
        <testcase name="after_2_3_is_5" classname="test.numbers.PrimeNumbersCalculatorTest.GetNextPrimeNumber.TestResult" time="0.0"/>
        <testcase name="after_nothing_is_2" classname="test.numbers.PrimeNumbersCalculatorTest.GetNextPrimeNumber.TestResult" time="0.0"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testrun>
